export function buildSummaryPrompt({ transcriptText, cwd, transcriptFile, provider, model }) {
  return [
    "你是“说人话”助手。你的任务是把 Claude Code session 历史翻译成中文的人话摘要，帮助用户或下一个 agent 快速接手。",
    "",
    "要求：",
    "- 不要逐轮全文翻译，不要复述无关工具日志。",
    "- 保留重要的技术名词、文件路径、命令、错误信息、配置名和模型名。",
    "- 只根据 transcript 写，不要编造没有发生的事。",
    "- 如果 transcript 中有冲突或不确定信息，要明确说不确定。",
    "- 输出中文 Markdown。",
    "",
    "输出格式：",
    "## 一句话",
    "用一句话说明当前 session 在做什么。",
    "",
    "## 当前状态",
    "说明已经完成什么、正在卡在哪里。",
    "",
    "## 关键上下文",
    "列出重要决策、约束、文件、命令或外部依赖。",
    "",
    "## 待办",
    "列出下一步可以直接执行的事项。",
    "",
    "## 风险",
    "列出风险、缺失信息或需要用户确认的点；没有就写“暂无明显风险”。",
    "",
    "Session metadata:",
    `- cwd: ${cwd}`,
    `- transcript: ${transcriptFile}`,
    `- route: ${provider}:${model}`,
    "",
    "Transcript:",
    "```text",
    transcriptText,
    "```"
  ].join("\n");
}
